// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/sharexp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message sent when text changes
type TextUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextUpdate) Reset() {
	*x = TextUpdate{}
	mi := &file_proto_sharexp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextUpdate) ProtoMessage() {}

func (x *TextUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharexp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextUpdate.ProtoReflect.Descriptor instead.
func (*TextUpdate) Descriptor() ([]byte, []int) {
	return file_proto_sharexp_proto_rawDescGZIP(), []int{0}
}

func (x *TextUpdate) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TextUpdate) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Acknowledgement for SendUpdate RPC
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_sharexp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharexp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_sharexp_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// Empty message
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_sharexp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharexp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_sharexp_proto_rawDescGZIP(), []int{2}
}

var File_proto_sharexp_proto protoreflect.FileDescriptor

const file_proto_sharexp_proto_rawDesc = "" +
	"\n" +
	"\x13proto/sharexp.proto\x12\asharexp\"C\n" +
	"\n" +
	"TextUpdate\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x15\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\a\n" +
	"\x05Empty2v\n" +
	"\vSyncService\x12/\n" +
	"\n" +
	"SendUpdate\x12\x13.sharexp.TextUpdate\x1a\f.sharexp.Ack\x126\n" +
	"\rStreamUpdates\x12\x0e.sharexp.Empty\x1a\x13.sharexp.TextUpdate0\x01B\x15Z\x13sharexp/proto;protob\x06proto3"

var (
	file_proto_sharexp_proto_rawDescOnce sync.Once
	file_proto_sharexp_proto_rawDescData []byte
)

func file_proto_sharexp_proto_rawDescGZIP() []byte {
	file_proto_sharexp_proto_rawDescOnce.Do(func() {
		file_proto_sharexp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sharexp_proto_rawDesc), len(file_proto_sharexp_proto_rawDesc)))
	})
	return file_proto_sharexp_proto_rawDescData
}

var file_proto_sharexp_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_sharexp_proto_goTypes = []any{
	(*TextUpdate)(nil), // 0: sharexp.TextUpdate
	(*Ack)(nil),        // 1: sharexp.Ack
	(*Empty)(nil),      // 2: sharexp.Empty
}
var file_proto_sharexp_proto_depIdxs = []int32{
	0, // 0: sharexp.SyncService.SendUpdate:input_type -> sharexp.TextUpdate
	2, // 1: sharexp.SyncService.StreamUpdates:input_type -> sharexp.Empty
	1, // 2: sharexp.SyncService.SendUpdate:output_type -> sharexp.Ack
	0, // 3: sharexp.SyncService.StreamUpdates:output_type -> sharexp.TextUpdate
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sharexp_proto_init() }
func file_proto_sharexp_proto_init() {
	if File_proto_sharexp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sharexp_proto_rawDesc), len(file_proto_sharexp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sharexp_proto_goTypes,
		DependencyIndexes: file_proto_sharexp_proto_depIdxs,
		MessageInfos:      file_proto_sharexp_proto_msgTypes,
	}.Build()
	File_proto_sharexp_proto = out.File
	file_proto_sharexp_proto_goTypes = nil
	file_proto_sharexp_proto_depIdxs = nil
}
